# Generated by Django 6.0.5 on 2026-05-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(help_text='One sentence summary', max_length=500)),
                ('business_problem', models.TextField()),
                ('tools_used', models.CharField(help_text='Comma-separated list', max_length=500)),
                ('key_features', models.TextField()),
                ('your_role', models.TextField()),
                ('biggest_challenge', models.TextField()),
                ('what_learned', models.TextField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('link', models.URLField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
