# Generated by Django 6.0.5 on 2026-05-07 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(choices=[('fas fa-code', 'Code'), ('fas fa-brain', 'Brain'), ('fas fa-cube', 'Cube'), ('fas fa-star', 'Star'), ('fas fa-database', 'Database'), ('fas fa-flask', 'Flask'), ('fas fa-cog', 'Cog'), ('fas fa-wrench', 'Wrench'), ('fas fa-tools', 'Tools'), ('fas fa-chart-line', 'Chart Line'), ('fas fa-rocket', 'Rocket'), ('fas fa-lightbulb', 'Lightbulb'), ('fas fa-laptop', 'Laptop'), ('fas fa-terminal', 'Terminal'), ('fas fa-book', 'Book'), ('fas fa-graduation-cap', 'Graduation Cap')], max_length=50)),
                ('color', models.CharField(choices=[('info', 'Blue (Info)'), ('warning', 'Yellow (Warning)'), ('success', 'Green (Success)'), ('danger', 'Red (Danger)'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('dark', 'Dark'), ('light', 'Light')], default='info', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on skills page')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the skill type')),
                ('skill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skilltype')),
            ],
            options={
                'ordering': ['skill_type', 'order', 'name'],
                'unique_together': {('name', 'skill_type')},
            },
        ),
    ]
