# Generated by Django 6.0.5 on 2026-05-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_skilltype_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='PNG image with transparent background recommended', upload_to='portraits/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Set to True to display this portrait. Only one should be active.')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
